[Enhancement] Instant Recall
HarbourMasters/2ship2harkinian pull request #589
Opened 2024-05-28 23:47 UTC by Patrick12115

Pressing B will instantly recall Zora Link's Fin Boomerangs when thrown.

2024-05-28 23:52 UTC, garrettjoecox reviewed
Oh he’s a hooks kinda guy

2024-05-29 01:55 UTC, garrettjoecox commented on mm/2s2h/BenGui/BenMenuBar.cpp
> +        if (UIWidgets::BeginMenu("Player Actions")) {
Maybe Items/Equipment might be better? I'm not sure what else would go in this category

2024-05-29 01:57 UTC, Patrick12115 commented on mm/2s2h/BenGui/BenMenuBar.cpp
> +        if (UIWidgets::BeginMenu("Player Actions")) {
I originally started using that when I did Instant Putaway, but it could probably go under Items/Equipment too

2024-06-04 13:07 UTC, inspectredc requested changes, later dismissed
Looks good, just one small thing re: the input

2024-06-04 13:07 UTC, inspectredc commented on mm/2s2h/Enhancements/Equipment/InstantRecall.cpp
> +                if (gPlayState->state.input->cur.button == BTN_B) {
this should be using CHECK_BTN_ALL, otherwise this will only return true if only the b button and nothing else is being held. I'm wondering if it should be using press instead of cur too

```suggestion
                if (CHECK_BTN_ALL(gPlayState->state.input->cur.button, BTN_B)) {
```

2024-07-22 16:10 UTC, Archez commented on mm/2s2h/Enhancements/Equipment/InstantRecall.cpp
> +
It looks like moving the boomerangs position is unnecessary if we are also calling `Actor_Kill` on them at the same time. The boomerangs get cleaned up without issue.

```suggestion
```

2024-07-22 16:11 UTC, Archez commented on mm/2s2h/Enhancements/Equipment/InstantRecall.cpp
> +                if (gPlayState->state.input->cur.button == BTN_B) {
I agree, and yeah I think `press` would be better to use as well.

```suggestion
                if (CHECK_BTN_ALL(gPlayState->state.input->press.button, BTN_B)) {
```

2024-08-19 02:15 UTC, Archez approved these changes
Pulled in latest develop and applied the suggested changes. This should be good to go now 👍

2024-08-19 03:24 UTC, merged